import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  LayoutDashboard,
  Menu,
  Moon,
  Sun,
  Building2,
  Briefcase,
  Users,
  CreditCard,
  Settings,
  HelpCircle,
  Activity,
  RefreshCw,
  BarChart3,
  Loader2,
  Search,
  X,
  ChevronRight,
  AlertCircle,
  Inbox,
  RotateCcw,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  AlertTriangle,
  PanelLeftClose,
  Landmark,
  Receipt,
  LifeBuoy,
  SlidersHorizontal,
  ClipboardList,
  House,
  Palette,
  Store,
  Plug,
  Library,
} from 'lucide-angular';

/**
 * Tree-shaken Lucide set for admin shell + design system primitives.
 */
@NgModule({
  imports: [
    LucideAngularModule.pick({
      LayoutDashboard,
      Menu,
      Moon,
      Sun,
      Building2,
      Briefcase,
      Users,
      CreditCard,
      Settings,
      HelpCircle,
      Activity,
      RefreshCw,
      BarChart3,
      Loader2,
      Search,
      X,
      ChevronRight,
      AlertCircle,
      Inbox,
      RotateCcw,
      ChevronLeft,
      ChevronUp,
      ChevronDown,
      ChevronsUpDown,
      AlertTriangle,
      PanelLeftClose,
      Landmark,
      Receipt,
      LifeBuoy,
      SlidersHorizontal,
      ClipboardList,
      House,
      Palette,
      Store,
      Plug,
      Library,
    }),
  ],
  exports: [LucideAngularModule],
})
export class RepIconsModule {}
